language: node_js 
node_js:
    - "14"

before_script:
    - npm run build
    - cat dist/index.js
    - cat dist/index.d.ts

deploy:
    edge: true
    provider: npm
    email: "$NPM_EMAIL"
    api_key: "$NPM_TOKEN"
    cleanup: true